import {
  Code,
  FileCode,
  Globe,
  Database,
  Cpu,
  BrainCircuit,
  Bot,
  Zap,
  Layout,
  TestTube,
  ShieldAlert,
  GraduationCap,
  Award,
  TrendingUp,
} from 'lucide-react';

export const portfolioData = {
  personalInfo: {
    name: "ABDUL REHMAN",
    titles: [
      "AI Automation Engineer",
      "Software Engineer",
      "Full Stack Developer",
      "LangChain Expert",
      "RAG Engineer",
      "AI Solutions Engineer",
      "Prompt Engineer",
      "Automation Specialist",
    ],
    description:
      "Dynamic and results-driven AI Automation Engineer and Software Engineer with comprehensive professional experience spanning enterprise workflow automation, full-stack development, and business operations. Adept at designing and deploying robust AI pipelines utilizing LangChain, RAG architectures, Pinecone, and multiple LLM APIs.",
    contact: {
      email: "abdulrehmanazeem23@gmail.com",
      phone: "0311-6677866",
      github: "https://github.com/abdulrehmanazeem23-coder",
      portfolio: "#",
      location: "Islamabad, Pakistan",
    },
  },
  stats: [
    { label: "Projects", value: "20+" },
    { label: "AI Automations", value: "10+" },
    { label: "Enterprise Systems", value: "5+" },
    { label: "Years Learning", value: "3+" },
    { label: "Passion", value: "100%" },
  ],
  about: {
    education: {
      degree: "BS Software Engineering",
      institution: "Capital University of Science & Technology (CUST)",
      cgpa: "3.0",
      semester: "Completed 6th Semester",
    },
    story:
      "I am a Software Engineer and AI Automation Specialist passionate about solving real-world business problems. While pursuing my BS in Software Engineering at CUST, I have actively worked in professional roles spanning business operations, software development, and AI engineering. As a self-learner and open-source contributor, I love bridging the gap between business operations and bleeding-edge AI technologies to drive massive automation and efficiency.",
  },
  experience: [
    {
      company: "EHA Pharma",
      role: "Stock & Accounts Manager",
      period: "September 2025 \u2013 Present",
      location: "Islamabad",
      responsibilities: [
        "Orchestrate comprehensive inventory management and stock reconciliation for a high-volume pharmaceutical distribution office.",
        "Administer end-to-end accounts management, ensuring precise financial record keeping and regulatory DRAP documentation compliance.",
        "Streamline distribution operations, order processing, and customer order management to optimize supply chain efficiency.",
      ],
    },
    {
      company: "Kanel Pharma",
      role: "Imports Manager",
      period: "June 2025 \u2013 August 2025",
      location: "Rawat",
      responsibilities: [
        "Directed international procurement operations, ensuring seamless execution of import documentation and customs clearance.",
        "Managed vendor relationships, international business communication, and rigorous shipment tracking.",
        "Coordinated complex banking documentation, Letters of Credit, and payment follow-ups in alignment with international trade regulations.",
      ],
    },
    {
      company: "Cogilent Solutions",
      role: "Frontend Design Intern",
      period: "July 2024 \u2013 August 2024",
      location: "On-site",
      responsibilities: [
        "Designed intuitive UI/UX workflows and responsive prototypes utilizing Figma to elevate end-user experiences.",
        "Collaborated effectively with cross-functional engineering teams to translate wireframes into interactive design components.",
      ],
    },
    {
      company: "Kanel Pharma",
      role: "Accounts Employee",
      period: "June 2023 \u2013 September 2023",
      location: "Rawat",
      responsibilities: [
        "Executed critical accounting tasks including invoice management, precise data entry, and meticulous financial record maintenance.",
      ],
    },
  ],
  projects: [
    {
      title: "Bid Response Engine",
      description: "Automated bid response system utilizing RAG and LangChain, reducing manual proposal evaluation time significantly.",
      technologies: ["RAG", "LangChain", "Next.js", "TypeScript", "Python"],
      category: "Enterprise AI",
      status: "Production",
      difficulty: "Hard",
      github: "https://github.com/abdulrehmanazeem23-coder/bid-response-engine",
      demo: "#",
      featured: true,
      businessImpact: "Reduced a 40-60 hour manual enterprise process down to minutes.",
    },
    {
      title: "AI Hiring Automation",
      description: "Enterprise-grade recruitment platform automating candidate screening using LLMs and n8n workflows.",
      technologies: ["n8n", "OpenAI GPT-4o", "Workflow Automation"],
      category: "Automation",
      status: "Deployed",
      difficulty: "Hard",
      github: "https://github.com/abdulrehmanazeem23-coder/ai-hiring-automation",
      demo: "#",
    },
    {
      title: "Competitor Intelligence System",
      description: "Market analysis tool leveraging OpenAI APIs to aggregate and analyze competitor data.",
      technologies: ["OpenAI API", "Python", "Data Extraction"],
      category: "Enterprise AI",
      status: "Deployed",
      difficulty: "Medium",
      github: "https://github.com/abdulrehmanazeem23-coder",
      demo: "#",
    },
    {
      title: "Customer Email Automation",
      description: "Automated incoming customer order processing via Gmail API and n8n. Eliminated manual data entry.",
      technologies: ["n8n", "Gmail API", "Workflow Automation"],
      category: "Automation",
      status: "Deployed",
      difficulty: "Medium",
      github: "https://github.com/abdulrehmanazeem23-coder",
      demo: "#",
    },
    {
      title: "AI Calendar Booking",
      description: "AI agent to categorize incoming emails and seamlessly schedule appointments via Calendar API.",
      technologies: ["AI Agents", "Calendar API", "n8n"],
      category: "Automation",
      status: "Deployed",
      difficulty: "Medium",
      github: "https://github.com/abdulrehmanazeem23-coder",
      demo: "#",
    },
    {
      title: "Lead Generation Pipeline",
      description: "Automated outbound marketing pipeline that qualifies leads using AI and deploys hyper-personalized outreach campaigns.",
      technologies: ["LangChain", "LLMs", "n8n"],
      category: "Automation",
      status: "Deployed",
      difficulty: "Hard",
      github: "https://github.com/abdulrehmanazeem23-coder",
      demo: "#",
    },
    {
      title: "Law Firm RAG",
      description: "Secure vector search knowledge base using Pinecone and LangChain for legal document retrieval.",
      technologies: ["Pinecone", "LangChain", "RAG"],
      category: "Enterprise AI",
      status: "Production",
      difficulty: "Hard",
      github: "https://github.com/abdulrehmanazeem23-coder",
      demo: "#",
    },
    {
      title: "Nike + Wikipedia AI Agent",
      description: "Autonomous AI agents capable of fetching, summarizing, and reasoning over diverse public datasets.",
      technologies: ["AI Agents", "Semantic Search", "LLMs"],
      category: "Enterprise AI",
      status: "Deployed",
      difficulty: "Medium",
      github: "https://github.com/abdulrehmanazeem23-coder",
      demo: "#",
    },
    {
      title: "AI Facial Recognition Attendance",
      description: "Computer vision and machine learning system to automate employee attendance tracking.",
      technologies: ["Computer Vision", "Machine Learning", "Python"],
      category: "Computer Vision",
      status: "Completed",
      difficulty: "Medium",
      github: "https://github.com/abdulrehmanazeem23-coder",
      demo: "#",
    },
    {
      title: "SEVA Frontend",
      description: "Frontend design and development for the SEVA web application.",
      technologies: ["React", "TypeScript", "Tailwind CSS"],
      category: "Full Stack",
      status: "Completed",
      difficulty: "Medium",
      github: "https://github.com/abdulrehmanazeem23-coder",
      demo: "#",
    },
  ],
  skills: {
    programming: ["Python", "JavaScript", "TypeScript", "C++", "PHP", "SQL"],
    ai: ["OpenAI", "Claude", "Gemini", "DeepSeek", "LangChain", "Prompt Engineering", "RAG", "Pinecone", "Embeddings", "AI Agents", "Semantic Search"],
    automation: ["n8n (Expert)", "Workflow Automation", "REST APIs", "Webhooks", "Google APIs"],
    frameworks: ["React", "Next.js", "Node.js", "FastAPI", "Flask", "Bootstrap", "Streamlit"],
    testing: ["Selenium", "Playwright"],
    cloud: ["Docker", "AWS", "Google Cloud", "Railway", "Render", "Linux", "Ubuntu"],
    databases: ["MySQL", "SQLite", "Firebase", "Supabase", "Pinecone"],
    design: ["Figma", "Canva", "Adobe Illustrator", "Adobe Photoshop"],
  },
  certifications: [
    "AI Chatbot Development",
    "AI Prompt Engineering",
    "Frontend Development",
    "Graphic Designing",
    "Hackathon Participation",
  ],
  services: [
    { title: "AI Automation", description: "End-to-end business process automation using AI workflows.", icon: "Zap" },
    { title: "Workflow Automation", description: "Expert n8n architecture to connect your entire software stack.", icon: "Database" },
    { title: "LLM Applications", description: "Building custom ChatGPT-like applications tailored to your company.", icon: "BrainCircuit" },
    { title: "Full Stack Development", description: "Scalable, secure, and modern web applications from scratch.", icon: "Layout" },
    { title: "Prompt Engineering", description: "Advanced prompt design for consistent, high-quality LLM outputs.", icon: "Bot" },
    { title: "Enterprise AI", description: "Deploying RAG pipelines for secure internal knowledge retrieval.", icon: "Cpu" },
  ]
};
